/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("POsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThePOsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThePOsListGenerated.onFilterBar().iCheckFilterField("{i18n>POId}");
            Then.onThePOsListGenerated.onFilterBar().iCheckFilterField("{i18n>ComapanyName}");
            Then.onThePOsListGenerated.onFilterBar().iCheckFilterField("GROSS_AMOUNT");
            Then.onThePOsListGenerated.onFilterBar().iCheckFilterField("{i18n>OverallStatus}");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onThePOsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onThePOsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onThePOsListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThePOsListGenerated.onTable().iCheckColumns(undefined, {"4":{"header":"Boost"},"PO_ID":{"header":"{i18n>POId}"},"PARTNER_GUID/COMPANY_NAME":{"header":"{i18n>ComapanyName}"},"PARTNER_GUID/ADDRESS_GUID/COUNTRY":{"header":"{i18n>Country}"},"GROSS_AMOUNT":{"header":"GROSS_AMOUNT"},"OverallStatus":{"header":"OverallStatus"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onThePOsListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onThePOsListGenerated.onTable().iCheckRows();

            When.onThePOsListGenerated.onTable().iPressRow(0);
            Then.onThePOsObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});