/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("POsObjectPageObjectPage journey");

        opaTest("Navigate to POsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onThePOsListGenerated.onFilterBar().iExecuteSearch();

            Then.onThePOsListGenerated.onTable().iCheckRows();
            When.onThePOsListGenerated.onTable().iPressRow(0);

            Then.onThePOsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThePOsObjectPageGenerated.iCheckNumberOfSections(2);
            When.onThePOsObjectPageGenerated.iPressSectionIconTabFilterButton("Facets::0");
            Then.onThePOsObjectPageGenerated.iCheckSection({ section: "Facets::0" });
            When.onThePOsObjectPageGenerated.iPressSectionIconTabFilterButton("Items::LineItem");
            Then.onThePOsObjectPageGenerated.iCheckSection({ section: "Items::LineItem" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});